<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/04_Operaciones_Basicas_y_Broadcasting.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


# 04 — Operaciones básicas y Broadcasting

- Aritmética elemento a elemento
- Comparaciones
- Producto matricial `@`
- Broadcasting en operaciones



In [1]:
import numpy as np

x = np.array([-1,0,1,2])
(x*2, x**2, x+2, -x)


(array([-2,  0,  2,  4]),
 array([1, 0, 1, 4]),
 array([1, 2, 3, 4]),
 array([ 1,  0, -1, -2]))

In [5]:
# Comparaciones y where
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
np.where(a == b)


(array([0, 3, 4]),)

In [6]:
# Producto matricial
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[2,3,4],[5,6,7],[8,9,10]])
A @ B


array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [11]:
# Broadcasting
v = np.arange(3)
M = np.ones((4,3))
M + v


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])