<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/05_Reshape_Ejes_y_Agregaciones.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


# 05 — Reshape, Ejes y Agregaciones

- `reshape` y volver a 1D
- `axis` en `sum`/`mean`
- Función auxiliar para explorar ejes



In [1]:
import numpy as np

# reshape y volver a plano
arr = np.arange(10)
M = arr.reshape(2,5)
flat = M.reshape(-1)
arr, M, flat


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [6]:
# agregaciones y axis
A = np.array([[1,2,3],[4,5,6]])
(
    A,
    np.sum(A),
    np.sum(A, axis=0),  # por columnas
    np.sum(A, axis=1),  # por filas
    np.mean(A),
    np.mean(A, axis=0),
    np.mean(A, axis=1),
)


(array([[1, 2, 3],
        [4, 5, 6]]),
 np.int64(21),
 array([5, 7, 9]),
 array([ 6, 15]),
 np.float64(3.5),
 array([2.5, 3.5, 4.5]),
 array([2., 5.]))

In [11]:
def explore_axis(v: np.ndarray, axis: int | None):
    w = np.sum(v, axis=axis)
    print(f"axis={axis} -> shape={w.shape}, original={v.shape}")
    return w

T = np.array([[[1,2,3],[-1,-2,-3]], [[-4,-5,-6],[4,5,6]]])
(
    T,
explore_axis(T, 0),
explore_axis(T, 1),
explore_axis(T, 2),
explore_axis(T, None)
)

axis=0 -> shape=(2, 3), original=(2, 2, 3)
axis=1 -> shape=(2, 3), original=(2, 2, 3)
axis=2 -> shape=(2, 2), original=(2, 2, 3)
axis=None -> shape=(), original=(2, 2, 3)


(array([[[ 1,  2,  3],
         [-1, -2, -3]],
 
        [[-4, -5, -6],
         [ 4,  5,  6]]]),
 array([[-3, -3, -3],
        [ 3,  3,  3]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[  6,  -6],
        [-15,  15]]),
 np.int64(0))